### ISSUE TITLE
Possible collaboration

### ISSUE THREAD

**Issue by alexander0042** [bakobako/pirate-weather-python#1]
Hi, 

Thank you so much for putting this together! It's exactly the sort of update that the Dark Sky API toolkit needed, and having it in Pip is awesome. 

I was wondering if you'd be open to adding me as a collaborator to this repository (I'm the dev of the main API)? I'm happy to submit PRs as things come up, but I was thinking it might be easier to have us both do it? Totally up to you, but wanted to extend the offer.

Thanks,
Alexander

**Comment by bakobako** [comment]
Hi Alexander,

Thanks for making the API. I have sent you the collaboration request :) 

Best,
Adam

**Comment by alexander0042** [comment]
Amazing! Thank you so much
